manala/manala-recipes

elao.app/.manala.yaml, elao.app/.manala.yaml.tmpl.dist, elao.app/.manala/docker/Dockerfile.tmpl, elao.app/README.md
Allow symfony cli to be installed, for the win:
- functionnal tests without nginx/php-fpm (https://symfony.com/doc/current/setup/symfony_server.html)
- security checks (https://symfony.com/doc/current/setup.html#checking-security-vulnerabilities)
=> [elao.app] Symfony cli integration

elao.app/.manala/make/Makefile.tmpl, elao.app/.manala/make/make.try.mk, elao.app/README.md
Use `try..finally` algorithm in your makefile targets :)
=> [elao.app] Introduce "try_finally" make function

elao.app/.manala/jenkins/Jenkinsfile.tmpl, elao.app/README.md
Simply let your build artifacts (such as logs) available in jenkins :)
=> [Elao - App] Handle jenkins artifacts

elao.app/.manala/make/make.docker.mk.tmpl, elao.app/README.md
See: https://github.com/docker/for-mac/issues/410
=> [Elao - App] Ssh agent available in docker on osx

elao.infra/.manala.yaml, elao.infra/.manala/docker/docker-compose.yaml.tmpl
=> Allow to create multiple infra stacks

elao.app/.manala.yaml, elao.app/.manala/jenkins/Jenkinsfile.tmpl
Be ready for https://github.com/manala/manala/pull/5
=> [Elao - App] Validation annotations

elao.infra/.manala/docker/Dockerfile.terraform.tmpl, elao.infra/.manala/docker/docker-compose.yaml.tmpl, elao.infra/.manala/docker/etc/terraform/zshrc
- upgrade provider openstack v1.26.0
- add provider ovh v0.7.0
- add provider template v2.1.2
- add public cloud project name in zsh prompt
=> [Elao - Infra] Upgrade terraform + add ovh plugin

elao.app/README.md
Using $PATH based pah could lead to security issues
=> [Elao - App] Use systemctl fullpath

elao.app/.manala/make/Makefile.tmpl, elao.app/.manala/make/make.help.mk, elao.app/.manala/make/make.text.mk, elao.infra/.manala/make/make.help.mk, elao.infra/.manala/make/make.text.mk
Before (indentation was arbitrarily set to 20)
```
App:
setup:               Setup environment & Install & Build application
update:              Update environment
update-ansible:      Update ansible
provision:           Provision environment
provision-nginx:     Provision nginx
provision-php:       Provision php
install:             Install application
build:               Build application
foo-bar-baz-qux-quux-corge: Grault garply waldo fred
```
After
```
App:
setup:                      Setup environment & Install & Build application
update:                     Update environment
update-ansible:             Update ansible
provision:                  Provision environment
provision-nginx:            Provision nginx
provision-php:              Provision php
install: …
```
=> Help auto indentation

elao.app/.manala.yaml, elao.app/.manala.yaml.tmpl.dist, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/.manala/ansible/roles/system/defaults/main.yaml, elao.app/.manala/ansible/roles/system/tasks/main.yaml, elao.app/README.md
`.manala.yaml`
```
##########
##########
system:
...
influxdb:
version: "*"
databases:
- app
users:
- database: app
name: app
password: app
privileges:
- database: app
user: app
grant: ALL
config:
- reporting-disabled: true
```
=> [Elao - App] Influxdb support

elao.app/.manala/Makefile.tmpl
Allow to provision Supervisor configuration specifically.
=> [Elao - App] make provision.supervisor

elao.app/.manala.yaml
Fixes #74 
(pas de comportement spécial hardcodé en fonction de ce mode de ce que je vois ?)
=> Free release "mode" config

elao.app/.manala/github/docker-compose.yaml.tmpl
Companion PR for https://github.com/Elao/manala-ci-action/pull/2
=> Remove local registry & configure manala_ci build context using docker-compose

elao.app/.manala/vagrant/bin/setup.sh.tmpl
Group apt purge commands to speed up a bit the setup phase
=> [Elao - App] Group purge commands

elao.app/README.md
=> [Elao - App] Typos

elao.app/.manala.yaml, elao.app/.manala/ansible/inventories/deploy.yaml.tmpl, elao.app/README.md
Just like `release_removed`, but for deployment phase
=> [Elao - App] Add "deploy_removed" release parameter

elao.app/.manala/Makefile.tmpl, elao.app/.manala/ansible/inventories/release.yaml.tmpl
In some cases, we just want to deploy the good ol'way, without releases :)
=> [Elao - App] Make release phase conditionnal

elao.app/.manala/github/docker-compose.yaml.tmpl
Relates to https://github.com/Elao/wotol/pull/1166/checks?check_run_id=1880428761#step:8:10
> "host" network_mode is incompatible with port_bindings
which appeared suddenly
To test before merge
=> Fix conflict between network_mode: host & ports config

elao.app/.manala/ansible/inventories/system.yaml.tmpl
Update apt packages during provisionning
=> [Elao - App] Apt update

elao.app/.manala.yaml, elao.app/_helpers.tmpl
so that funky modes could be given to releases, such as "staging-1"
And to celebrate, let's back to 2013
=> [Elao - App] Unleash release mode constraints

elao.app/.manala/ansible/inventories/deploy.yaml.tmpl, elao.app/.manala/ansible/inventories/release.yaml.tmpl
=> [Elao - App] Simplify release inventories internals

elao.app/.manala.yaml, elao.app/.manala/Makefile.tmpl, elao.app/.manala/ansible/inventories/deploy.yaml.tmpl, elao.app/.manala/ansible/inventories/release.yaml.tmpl, elao.app/README.md, elao.app/_helpers.tmpl
Too specific, too hard, not open at all, that was definitively *NOT* a good idea...
See: https://github.com/manala/manala-recipes/pull/100
=> [Elao - App] Remove release hosts group feature

docs/app/composer.lock, docs/app/package-lock.json, docs/app/templates/base.html.twig
=> Docs cleanup

elao.app/.manala.yaml, elao.app/.manala.yaml.tmpl, lazy.symfony/.manala.yaml, lazy.symfony/.manala.yaml.tmpl
First step:
- introduce `template` parameter
- Copy manifest dist templates
See: https://github.com/manala/manala-recipes/pull/120
=> Init project manifest template #1

elao.app/.manala.yaml, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/.manala/ansible/system.yaml, elao.app/README.md
Handle the following config :
```yaml
system:
network:
hosts:
127.0.0.1: "foobar.fr"
```
=> [Elao - App] Network hosts

elao.app/README.md
=> [Elao - App] Box update doc

elao.app/.manala/Dockerfile.tmpl, elao.app/.manala/Makefile.tmpl, elao.app/.manala/Vagrantfile.tmpl, elao.app/.manala/ansible/system.yaml, elao.app/.manala/ansible/templates/ohmyzsh/.zshrc.j2, elao.app/.manala/docker/make.mk.tmpl, elao.app/.manala/vagrant/make.mk
Believe me, this is *REALLY* boring.
You don't want to know how, but it's working.
And of course, this is not useless, this is mainly to harmonize with "lazy.*" recipes (see: https://github.com/manala/manala-recipes/pull/136)
=> [Elao - App] Some boring directory naming refactoring

elao.app/.manala/Dockerfile.tmpl
> Dockerfile parse error line 77: unknown instruction: DIR
=> Fix elao.app WORKDIR in Dockerfile

elao.app/.manala/make/text.mk
Add confirm conditionals make helpers
```
foo:
$(call confirm_if, $(FOO), Confirm foo)
$(call confirm_if_not, $(BAR), Not confirm bar)
```
=> [Elao - App] Confirm conditionals

elao.app/Makefile.dist
=> [Elao - App] Fix assets build options

lazy.ansible/.manala.yaml
=> [Lazy - Ansible] Update ansible

lazy.ansible/.manala/Dockerfile.tmpl, lazy.kubernetes/.manala/Dockerfile.tmpl, lazy.symfony/.manala/Dockerfile.tmpl
=> [Lazy] Update starship

lazy.symfony/.manala/Dockerfile.tmpl
=> [Lazy - Symfony] Update ansistrano

elao.app/.manala/Dockerfile.tmpl, elao.app/.manala/Jenkinsfile.tmpl, elao.app/.manala/docker/bin/entrypoint.sh
Fix recent issues with jenkins on kubernetes, where docker is no longer the container handler
=> [Elao - App] Jenkins rebirth

lazy.kubernetes/.manala/Dockerfile.tmpl
=> [Lazy Kubernetes] Add jq

elao.app.docker/.manala.yaml, elao.app.docker/.manala.yaml.tmpl, elao.app.docker/.manala/Makefile.tmpl, elao.app.docker/.manala/ansible/inventories/system.yaml.tmpl, elao.app.docker/.manala/docker/compose/development.yaml.tmpl, elao.app.docker/.manala/docker/make.mk, elao.app.docker/MIGRATION.2022-02.md, elao.app.docker/README.md, elao.app.docker/_helpers.tmpl
⚠️ ⚠️ ⚠️ ⚠️ 
BC BREAKS !!!
⚠️ ⚠️ ⚠️ ⚠️ 
in `.manala.yaml`
Before
```
project:
name: foo
ports: 12300
```
After:
```
project:
name: foo
ports_prefix: 123
```
=> [Elao - App - Docker] Ports prefix

elao.app.docker/.manala.yaml, elao.app.docker/.manala/Jenkinsfile.tmpl, elao.app.docker/.manala/jenkins/Jenkinsfile.tmpl, elao.app.docker/MIGRATION.2022-02.md, elao.app.docker/README.md
⚠️ ⚠️ ⚠️ ⚠️ 
BC BREAKS !!!
⚠️ ⚠️ ⚠️ ⚠️ 
Jenkins integration pipeline has now its dedicated entry in `.manala.yaml`:
```diff
###############
###############
integration:
-     app: foo
-     tasks:
-       - shell: make install@integration
-       ...
-     ...
+     jenkins:
+         pipeline:
+             app: foo
+             tasks:
+               - shell: make install@integration
+               ...
+             ...
```
=> [Elao - App - Docker] Integration - Jenkins

elao.app.docker/.manala.yaml, elao.app.docker/.manala/Makefile.tmpl, elao.app.docker/README.md
Give pleasure to your lovely users, showing them the url to visit after a successful deploy.
.manala.yaml
```yaml
deliveries:
- ...
deploy_url: https://foo.com
```
```shell
$ make deploy.foo@bar
...
(っ◕‿◕)っ Visit https://foo.com
```
=> [Elao - App - Docker] Deliveries deploy url

elao.app.docker/.manala.yaml, elao.app.docker/.manala/Makefile.tmpl, elao.app.docker/.manala/docker/compose/integration.yaml.tmpl, elao.app.docker/.manala/github/deliveries/README.md.tmpl, elao.app.docker/.manala/github/deliveries/action.yaml.tmpl, elao.app.docker/.manala/github/integration/README.md.tmpl, elao.app.docker/.manala/github/integration/action.yaml.tmpl, elao.app.docker/.manala/github/system/action.yaml
=> [Elao - App - Docker] GitHub Actions

elao.app.docker/.manala/github/deliveries/README.md.tmpl, elao.app.docker/.manala/github/integration/README.md.tmpl
Some advices in the generated integration Readme so I hope everyone will adapt their workflows to their project and learn more about Github actions instead of just copy/pasting 😄
=> [Elao - App - Docker] Integration workflow advices

docs/app/Makefile, docs/app/composer.json, docs/app/composer.lock, docs/app/config/packages/stenope.yaml, docs/app/config/services.yaml, docs/app/package-lock.json, docs/app/src/Controller/MigrationController.php, docs/app/src/Model/Migration.php, docs/app/src/Stenope/Processor/DefaultTocProcessor.php, docs/app/src/Stenope/Processor/MigrationRecipeProcessor.php, docs/app/symfony.lock, docs/app/templates/migrations/show.html.twig, docs/app/templates/recipes/show.html.twig, elao.app.docker/MIGRATION.2022-02.md
https://manala.github.io/manala-recipes/migrations/elao.app.docker/MIGRATION.2022-02/
=> [Docs] Expose migrations files on static site

elao.app.docker/.manala/github/deliveries/README.md.tmpl
=> [Elao - App - Docker] Github actions concurency

lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/Dockerfile.tmpl, lazy.kubernetes/.manala/templates/profile.d/message.sh.tmpl
Helm plugins support:
`.manala.yaml`
```
system:
...
helm:
...
plugins:
- url: https://github.com/databus23/helm-diff
version: 3.4.2
- url: https://github.com/jkroepke/helm-secrets
version: 3.13.0
```
=> [Lazy - Kubernetes] Helm plugins

lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/Dockerfile.tmpl, lazy.kubernetes/.manala/templates/profile.d/message.sh.tmpl
Introduce [Helmfile](https://helmfile.readthedocs.io/en/latest/)
`.manala.yaml`:
```
...
helmfile:
version: 0.144.0
...
```
Note that your helmfile usage could need `diff` and/or `secrets`  helm plugins.
`.manala.yaml`:
```
...
helm:
version: 3.7.1
plugins:
- url: https://github.com/databus23/helm-diff
version: 3.4.2
- url: https://github.com/jkroepke/helm-secrets
version: 3.13.0
...
```
=> [Lazy - Kubernetes] Helmfile

lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/Dockerfile.tmpl
- **kubectl**
* `1.24.1`
* `1.23.4` -> `1.23.7`
* `1.22.3` -> `1.22.10`
* `1.21.6` -> `1.21.13`
* `1.20.12` -> `1.20.15`
- **helm**
* `3.9.0`
* `3.8.0` -> `3.8.2`
* `3.7.1` -> `3.7.2`
- **k9s**
* `0.24.15` -> `0.25.18`
- **stern**
* `1.20.1` -> `1.21.0`
- **popeye**
* `0.9.7` -> `0.10.0`
- **vault**
* `1.10.4`
* `1.9.3` -> `1.9.7`
* `1.8.4` -> `1.8.12`
- **rclone**
* `1.57.0` -> `1.58.1`
- **openstack**
* `5.6.0` -> `5.8.0`
- **swift**
* `3.12.0` -> `4.0.0`
- **keystone**
* `4.3.0` -> `4.5.0`
- **scw**
* `2.5.1` -> `2.5.2`
=> [Lazy - Kubernetes] Update components

elao.app.docker/.manala/ansible/roles/release/tasks/main.yml
=> [Elao - App - Docker] Verbose release remove

elao.app/.manala/ansible/collections/requirements.yaml
Since Manala 2.0.0 is for ansible >=2.10
=> [Elao.app] Set Manala collection version under 2.0.0

lazy.ansible/.manala.yaml, lazy.ansible/.manala/templates/profile.d/message.sh.tmpl, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/templates/profile.d/message.sh.tmpl, lazy.symfony/.manala.yaml, lazy.symfony/.manala/templates/profile.d/message.sh.tmpl
project`.manala.yaml`:
```
...
manala:
project: foo
help: |
whoever reads this
is a jerk
```
`$ manala up`
`$ make sh`:
```
|
\ _ /     Lazy - ???
-= (_) =-
/   \         _\/_
|           //o\  _\/_
_____ _ __ __ ____ _ | __/o\ _
=-=-_-__=_-= _=_=-=_,-'|"'""-|-,_
=- _=-=- -_=-=_,-"          |"
=- =- -=.--"
‣ ??? 1.2.3
‣ ??? 1.2.3
whoever reads this
is a jerk
00:00:00 lazy@??? ??? →
```
=> [Lazy] Project help message

lazy.ansible/.manala.yaml
- **ansible-lint**
* `6.5.2`
* `6.4.0`
- **molecule**
* `4.0.0` -> `4.0.1`
=> [Lazy - Ansible] Update components

elao.app.docker/.manala/github/deliveries/README.md.tmpl, elao.app.docker/.manala/github/env/README.md.tmpl, elao.app.docker/.manala/github/integration/README.md.tmpl, elao.app.docker/.manala/github/integration/action.yaml.tmpl
Contexte: https://github.com/Elao/mjc-ats/pull/879#discussion_r982851460
cc @quentin-brouillet
=> [Elao - App - Docker] Adds the env key to integration action

elao.app.docker/.manala.yaml
Nothing really interesting here....
A purely comestic order change, and some types switched from array to string (yes, an array with only one element don't deserve to be an array, it's just a fucking string)
=> [Elao - App - Docker] Cleanup schema tags

elao.app.docker/.manala/github/manala-up/README.md
A classic we already use on many projects
=> [Elao - App - Docker] Add sampled "Check .manala.yaml up-to-date" workflow

lazy.ansible/.manala/Makefile.tmpl, lazy.ansible/.manala/docker/make.mk.tmpl, lazy.kubernetes/.manala/Makefile.tmpl, lazy.kubernetes/.manala/docker/make.mk.tmpl, lazy.symfony/.manala/Makefile.tmpl, lazy.symfony/.manala/docker/make.mk.tmpl
Introduce makefile `DOCKER` variable to ease inside/outside container detection
=> [Lazy] Update makefile "if in container" detection

elao.app.docker/README.md
=> [Elao - App - Docker] Reword HTTPS section

elao.app.docker/.manala/ansible/system.yaml, elao.app.docker/.manala/ansible/templates/ngrok/ngrok.yml.j2, elao.app.docker/.manala/ansible/templates/ohmyzsh/functions/ngrok_http.j2
confusing, frustrating, irritating and useless
=> [Elao - App - Docker] No more ngrok system config file

elao.app.docker/Makefile.dist
Suggest some more targets & fine-grained targets that are useful on a daily basis when working on our projects.
=> [Elao - App - Docker] Add moar common make targets

elao.app.docker/.manala.yaml, elao.app.docker/README.md
See: https://github.com/manala/ansible-roles/pull/635
=> [Elao - App - Docker] Php 8.2

lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.symfony/.manala/docker/Dockerfile.tmpl
See: https://wiki.debian.org/DebianRepository/UseThirdParty
=> [Lazy] Remove apt-key usage

lazy.ansible/.manala.yaml, lazy.ansible/.manala.yaml.tmpl, lazy.ansible/.manala/etc/ansible/ansible.cfg.tmpl, lazy.ansible/.manala/etc/ssh/ssh_config.d/ssh_config.conf.tmpl
As easy as:
```yaml
...
system:
ssh:
config: |
#HashKnownHosts no
#StrictHostKeyChecking no
#LogLevel ERROR
Host *.example.com
User foo
ForwardAgent yes
ansible:
...
config: |
[defaults]
#force_color = True
#retry_files_enabled = False
[ssh_connection]
#pipelining = True
#control_path_dir = /tmp/ansible/cp
```
=> [Lazy - Ansible] Custom ssh & ansible config

lazy.kubernetes/.manala.yaml
- **kubectl**
* `1.26.1`
* `1.25.5` -> `1.25.6`
* `1.24.9` -> `1.24.10`
* `1.23.1` -> `1.23.16`
- **helm**
* `3.11.0`
- **helmfile**
* `0.149.0` -> `0.150.0`
- **aws**
* `2.9.16` -> `2.9.17`
=> [Lazy -Kubernetes] Update components

lazy.ansible/.manala/docker/compose.yaml.tmpl, lazy.kubernetes/.manala/docker/compose.yaml.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl
1) Useless in internal
2) Should be a user choice
=> [Lazy] Remove tmpfs /tmp

lazy.symfony/.manala.yaml
- **maildev**
* `2.0.0-beta3` -> `2.0.5`
=> [Lazy - Symfony] Update components

elao.app.docker/.manala/docker/compose/profile.development.yaml.tmpl
Ooops https://hub.docker.com/r/erikdubbelboer/phpredisadmin/tags?page=1&name=1.18.0
=> [Elao - App - Docker] Fix PhpRedisAdmin docker tag

elao.app.docker/.manala/ansible/ansible.mk
On the same spirit as `setup`:
```shell
make provision DEBUG=1
```
=> [Elao - App - Docker] Introduce ansible-playbook debug

elao.app.docker/.manala/docker/compose/init.sysv.yaml
=> [Elao - App - Docker] Useless /tmp tmpfs

.github/workflows/elao.app.docker.yaml, elao.app.docker/.manala.yaml, elao.app.docker/.manala/docker/Dockerfile.tmpl, elao.app.docker/_helpers.tmpl, elao.app.docker/test/.manala.yaml, elao.app.docker/test/Makefile, elao.app.docker/test/goss.yaml, elao.app.docker/test/public/index.php
This also includes goss installation to play these tests.
=> [Elao - App - Docker] Introduce tests

elao.app.docker/.manala/Makefile.tmpl, elao.app.docker/.manala/docker/docker.mk, lazy.ansible/.manala/Makefile.tmpl, lazy.ansible/.manala/docker/docker.mk, lazy.ansible/README.md, lazy.kubernetes/.manala/Makefile.tmpl, lazy.kubernetes/.manala/docker/docker.mk, lazy.kubernetes/README.md, lazy.symfony/.manala/Makefile.tmpl, lazy.symfony/.manala/docker/docker.mk, lazy.symfony/README.md
```shell
make sh DIR=/etc <<< pwd
/etc
```
=> [All] Custom working dir

.github/workflows/elao.app.docker.yaml, .github/workflows/lazy.ansible.yaml, .github/workflows/lazy.kubernetes.yaml, .github/workflows/lazy.symfony.yaml, elao.app.docker/.manala/github/system/run/action.yaml, elao.app.docker/.manala/github/system/setup/action.yaml, lazy.ansible/.manala.yaml, lazy.ansible/.manala/github/system/run/action.yaml, lazy.ansible/.manala/github/system/setup/action.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/github/system/run/action.yaml, lazy.kubernetes/.manala/github/system/setup/action.yaml, lazy.symfony/.manala.yaml, lazy.symfony/.manala/github/system/run/action.yaml, lazy.symfony/.manala/github/system/setup/action.yaml
=> [All] System github action

lazy.ansible/.manala.yaml, lazy.ansible/.manala.yaml.tmpl, lazy.ansible/.manala/etc/gitconfig.tmpl, lazy.ansible/test/.manala.yaml, lazy.ansible/test/goss.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala.yaml.tmpl, lazy.kubernetes/.manala/etc/gitconfig.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.kubernetes/test/goss.yaml, lazy.symfony/.manala.yaml, lazy.symfony/.manala.yaml.tmpl, lazy.symfony/.manala/etc/gitconfig.tmpl, lazy.symfony/test/.manala.yaml, lazy.symfony/test/goss.yaml
Example in project's `.manala.yaml` file:
```yaml
...
system:
...
git:
config: |
[safe]
directory = *
...
```
=> [Lazy] Git config

elao.app.docker/.manala.yaml, elao.app.docker/README.md, elao.app.docker/test/.manala.yaml
=> [Elao - App - Docker] Nodejs 20

elao.app.docker/README.md
=> [Elao - App - Docker] Complete cron configuration help

elao.app.docker/.manala/github/deliveries/deploy/action.yaml.tmpl, elao.app.docker/.manala/github/deliveries/release/action.yaml, elao.app.docker/.manala/github/deliveries/setup/action.yaml.tmpl, elao.app.docker/.manala/github/reset-stagings/README.md.tmpl
Fix wrongly calling `make releasestaging` without `@` ➜ `make release@staging`
=> [Elao - App - Docker] Fix single app deliveries

elao.app.docker/.manala/github/deliveries/deploy/action.yaml.tmpl, elao.app.docker/.manala/github/deliveries/setup/action.yaml.tmpl
cc @Tom32i (_I heard you've got some troubles with these lately_)
=> [Elao - App - Docker] Make the SSH key & deploy URLs config options properly optional

elao.app.docker/.manala/docker/Dockerfile.tmpl, elao.app.docker/test/goss.yaml
Combo !
- Switch from `ansible-core` to `ansible`,  so that common collections are already installed
- Implicit `ansible-core` update, now that ansible-galaxy awesome slowness seems to be fixed
=> [Elao - App - Docker] Update ansible 8.5.0

lazy.ansible/.manala/etc/profile.d/oh-my-bash.sh.tmpl, lazy.kubernetes/.manala/etc/profile.d/oh-my-bash.sh.tmpl, lazy.symfony/.manala/etc/profile.d/oh-my-bash.sh.tmpl
According to last git repository commits.
Nothing special, here...
=> [Lazy] Update oh-my-bash template

lazy.ansible/.manala.yaml, lazy.ansible/test/.manala.yaml
=> [Lazy - Ansible] Update terraform

elao.app.docker/.manala/docker/Dockerfile.tmpl
=> [Elao - App - Docker] Use ansible check mode marker

lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.ansible/test/goss.yaml, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/test/goss.yaml, lazy.symfony/.manala/docker/Dockerfile.tmpl, lazy.symfony/test/goss.yaml
- Gomplate `3.11.7` > `4.0.0`
- Direnv `2.33.0` > `2.34.0`
=> [Lazy] Update components

lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala.yaml.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/etc/profile.d/message.sh.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.kubernetes/test/goss.yaml
See: https://github.com/FiloSottile/age
`.manala.yaml`:
```
...
system:
...
age:
version: 1.2.0
```
=> [Lazy - Kubernetes] Age

elao.app.docker/.manala/docker/Dockerfile.tmpl, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.symfony/.manala/docker/Dockerfile.tmpl
So that the build can quickly fail in case of http 4xx/5xx errors
=> [All] Use fail curl arg

lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala.yaml.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/etc/profile.d/message.sh.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.kubernetes/test/goss.yaml
Deprecated since kubernetes 1.20
See: https://github.com/thyarles/knsk?tab=readme-ov-file#atention
=> [Lazy - Kubernetes] Remove knsk

lazy.ansible/.manala/etc/profile.d/message.sh.tmpl, lazy.kubernetes/.manala/etc/profile.d/message.sh.tmpl, lazy.symfony/.manala/etc/profile.d/message.sh.tmpl
Just add a trailing line after messages on login
=> [Lazy] Cleanup messages

lazy.ansible/.manala/etc/starship/starship.toml.tmpl, lazy.kubernetes/.manala/etc/starship/starship.toml.tmpl, lazy.symfony/.manala/etc/starship/starship.toml.tmpl
'cause it's really-really useless...
=> [Lazy] Disable starship direnv integration

elao.app.docker/.manala.yaml, elao.app.docker/test/.manala.yaml
Should be ok as of https://github.com/manala/ansible-roles/pull/716 ? 🤞🏻 
---
❌ https://github.com/manala/manala-recipes/actions/runs/12810438515/job/35717500896?pr=482#step:4:1694
> msg: 'TemplateNotFound: ''fpm_pools/sury/8.4/pools.conf.j2'' not found in search paths
=> [Elao - App - Docker] PHP 8.4 🤞

lazy.ansible/.manala.yaml, lazy.ansible/test/.manala.yaml
Now that debian trixie embed python 3.13, it's time to unleash recent ansible versions :)
- `2.19.0`
- `2.18.8`
- ~~`2.15.13`~~
- ~~`2.14.18`~~
=> [Lazy - Ansible] Update ansible component
