manala/manala-recipes

elao.app/.manala/jenkins/Jenkinsfile.tmpl, elao.app/README.md
This allows integration tasks to continue even if a stage fail. Integration will be in "unstable" state instead of "failed".
Fix https://github.com/manala/manala-recipes/issues/5
=> [elao.app] Introduce integration warn option

elao.app/.manala/jenkins/Jenkinsfile.tmpl, elao.app/README.md
Before:
```
- label: Integration
junit: report/junit/*.xml
parallel: true
tasks:
- label: Lint
tasks:
- shell: make lint.php-cs-fixer@integration
warn: true
- shell: make lint.twig@integration
warn: true
- shell: make lint.yaml@integration
warn: true
- label: Security
tasks:
- shell: make security.symfony@integration
warn: true
- shell: make security.yarn@integration
warn: true
- label: Test
tasks:
- shell: make test.phpunit@integration
warn: true
env:
DATABASE_URL: mysql://root@127.0.0.1:3306/app
APP_ELASTIC_SEARCH_HOST: 127.0.0.1
APP_ELASTIC_SEARCH_PORT: 9200
```
After:
```
- label: Integration
junit: report/junit/*.xml
parallel: true
warn: true
tasks:
- label: Lint
tasks:
- shell: make lint.php-cs-fixer@integration
- shell: make lint.twig@integration
- shell: make lint.yaml@integration …
```
=> [Elao - App] Recusrsively apply integration warns

elao.app/.manala.yaml
Environment variable could be either `string` or `integer`
=> [Elao - App] Env type

elao.app/.manala.yaml, elao.app/README.md
Note that mariadb is now promoted as the first mysqlalternative choice
=> [Elao - App] Supports MariaDB 10.4

elao.app/.manala.yaml, elao.app/.manala/jenkins/Jenkinsfile.tmpl
Both syntax availables, string or array.
```
integration
tasks:
...
- shell: foo
artifacts: var/logs/*.log
- shell: bar
artifacts:
- var/logs/*.log
- var/sync_reports/*.html
```
=> [Elao - App] Allow multiple jenkins artifacts

elao.app/.manala/ansible/deploy.inventory.yaml.tmpl, elao.app/.manala/ansible/roles/deploy/defaults/main.yml, elao.app/.manala/ansible/roles/deploy/tasks/strategy/git.yml, elao.app/.manala/make/Makefile.tmpl
Before:
```
$ make deploy@production
```
After:
```
$ make deploy@production
or/and
$ make deploy@production REF=v1.2.3
```
\o/
=> [Elao - App] Allow deploy ref specification

lazy.symfony/.manala.yaml, lazy.symfony/.manala/docker-compose.yaml.tmpl
Docker ports range can now be specified on a per project basis.
Default ports range (8080, 8306, 8300, 8025).
```
system:
ports: 8000
```
Punks-à-chiens ports range (9080, 9306, 9300, 9025)
```
system:
ports: 9000
```
...
=> [Lazy - Symfony] Docker ports range

elao.app/.manala/Dockerfile.tmpl, elao.app/.manala/vagrant/bin/setup.sh.tmpl
Numeric variables coming from terminal user interface (aka. drop down during "init" command) and yaml parsing (during "update" command) are not the same types.
First ones are "float64" as a result of json schema parsing, other ones ar "int".
A simple comparison in templates such as `{{ if eq .version 8 }}` leads to an error message during project init (`error calling eq: incompatible types for comparison`) because an "int" could not be compared to a "float64".
Such variables *MUST* be converted, with something like `{{ if eq (.version|int) 8 }}`
=> [Elao - App] System version incompatible types

elao.app/.manala/Dockerfile.tmpl, elao.app/.manala/ansible/inventories/deploy.yaml.tmpl, elao.app/.manala/ansible/inventories/release.yaml.tmpl, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/.manala/vagrant/bin/setup.sh.tmpl
Using `ANSIBLE_PYTHON_INTERPRETER` environment variables was not a good idea, given that some distant hosts could be on distributions unable to support python 3 or python 3 decent version (aka. jessie).
If environment/integration hosts let ansible python interpreter set to python 3 because they can support it, deployment become impossible on  retarded distributions, because `ANSIBLE_PYTHON_INTERPRETER` environment variables is applied on every fucking host.
A new approach is to define python interpreter in inventory variables, in a fixed version where it can be guessed, or on an `auto_silent` one for others (such as deployment hosts)
See: https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html
💋
=> [Elao - App] Fix ansible python interpreter

elao.app/.manala.yaml, elao.app/.manala.yaml.tmpl.dist, elao.app/.manala/Vagrantfile.tmpl, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/.manala/ansible/roles/system/defaults/main.yaml, elao.app/.manala/ansible/roles/system/tasks/main.yaml, elao.app/.manala/ansible/templates/mongodb/mongod.conf.j2, elao.app/README.md
Only versions 4.2/4.4, and no integration :)
Usage:
```
system:
...
mongodb:
version: 4.4
```
And zou !
(don't forget to enable the relating php extension ;) )
```
system:
...
php:
extensions:
...
- mongodb
```
🌴 ([mongo-express](https://github.com/mongo-express/mongo-express) is also activated as a docker image)
=> [Elao - App] Basic MongoDB support

elao.app/.manala/Dockerfile.tmpl
Useful to run the Docker image in a Github Action runner,
where the user uid/gid is 1001.
```shell
docker build .manala --build-arg UID=1001 --build-arg GID=1001
```
=> Allow to configure user uid/gid at build time

elao.app/.manala/ansible/templates/supervisor/app.conf.j2, elao.app/README.md
Support for supervisor groups: http://supervisord.org/configuration.html#group-x-section-settings
Usage example:
```yaml
supervisor:
configs:
- file: servers.conf
groups:
whatthetune:
programs:
- private
- hits
programs:
private:
command: node bin/server.js 8099 localhost http --privateServer --inspect=./influx.json
directory: /srv/app/server
hits:
command: node bin/server.js hits 8006 localhost http --inspect=./influx.json
directory: /srv/app/server
```
=> [Elao - App] Support supervisor groups

elao.app/.manala/ansible/templates/supervisor/app.conf.j2, elao.app/README.md
Add suport for "raw" supervisor configs.
Example:
```
supervisor:
configs:
- file: app_foo.conf
config: |
[program:foo]
command=/bin/foo
```
=> [Elao -App] Support supervisor raw configs

elao.app/.manala.yaml, elao.app/.manala/github/docker-compose.yaml.tmpl
This docker-compose file aims to be used in a Manala CI Github Action to start services & the local registry used for caching purposes (as currently done in one of our projects).
But we can discuss later about providing one for other purposes as well (dev, utils, ...).
=> [Elao - App] Generate docker-compose.yaml for Github Actions

elao.app/.manala/vagrant/bin/setup.sh.tmpl
As seen here (https://github.com/chef/bento/blob/be2ca582a3908fd2ec4648bd02523cf90f261683/packer_templates/debian/http/debian-9/preseed.cfg#L25) root account is disabled on bento debian boxes during preseed.
Having a root access is useful to debug and have an emergency shell access solution when regular vagrant user is blocked for any reasons.
=> [Elao - App] Enable root access

elao.app/.manala/vagrant/bin/setup.sh.tmpl
To allow seamless kernel package upgrades with virtualbox guest additions building, we must:
- ensure `make` package is installed
- upgrade kernel package AND install kernel headers package in the SAME time. Thanks god, after an apt update, an apt install command on an already installed package leads to its updates.
The process becomes:
1. apt update
2. apt install kernel (aka. update), kernel headers, and make
3. apt upgrade
=> [Elao - App] Cleanup kernel upgrades

elao.app/.manala.yaml, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/README.md
```
system:
....
php:
...
composer:
version: 1
```
Note: only composer version **1** is supported to handle legacy projects. If you want latest stable, don't specify version.
=> [Elao - App] Composer version

elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/README.md
When projects takes care of their sessions storage
```
system:
files:
...
- path: /srv/app/var/sessions
src: /srv/sessions
state: link_directory
```
=> [Elao - App] Support app sessions directory

elao.app/.manala/vagrant/bin/setup.sh.tmpl
As it leads to serious issues, just like having mariadb config alternative because `python-mysqldb` package is coming with `mariadb-common` dependency...
=> [Elao - App] Stop pre-installing ansible related packages

elao.app/.manala.yaml, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/.manala/ansible/templates/mysql/zz-mysqld.cnf.j2.tmpl, elao.app/README.md
Note that we have to set `default-authentication-plugin` to `mysql_native_password` to ensure users provisionning don't break under ansible 2.9
=> [Elao - App] MySQL 8.0 support

elao.app/.manala.yaml, elao.app/.manala/ansible/inventories/deploy.yaml.tmpl, elao.app/.manala/ansible/inventories/release.yaml.tmpl, elao.app/README.md
Give a way to specify git ref (hash, branch, tag, ...) for releases.
By default, this is master, or a combination of mod/app if `mode` is specified.
=> [Elao - App] Specify git ref

elao.app/.manala.yaml, elao.app/.manala/Makefile.tmpl, elao.app/.manala/ansible/inventories/deploy.yaml.tmpl, elao.app/.manala/ansible/inventories/release.yaml.tmpl, elao.app/README.md, elao.app/_helpers.tmpl
Deploy hosts can now be **optionnaly** grouped.
Before:
```
releases:
- mode: production
...
deploy_hosts:
- ssh_host: foo-1.com
- ssh_host: foo-2.com
- ssh_host: foo-2.bar.com
```
After:
```
releases:
- mode: production
...
deploy_hosts:
foo:
- ssh_host: foo-1.com
- ssh_host: foo-2.com
foo/bar:
- ssh_host: foo-2.bar.com
```
Makefile targets are still automatically generated.
=> [Elao - App] Deploy hosts groups

elao.app/.manala/ansible/templates/supervisor/app.conf.j2
=> [Elao - App] Fix supervisor ansible template

elao.app/.manala/Dockerfile.tmpl
Some debian packages are compressed using "xz" format (https://snapshot.debian.org/archive/debian/20190505T225241Z/pool/main/i/imagemagick/imagemagick-6-common_6.9.10.23%2Bdfsg-2.1_all.deb).
Installing them via related ansible module "apt" need the `xz-utils` package
=> [Elao - App] Support "xz" compressed debian packages in docker

elao.app/.manala/ansible/inventories/system.yaml.tmpl
Because php could simply not be used:)
=> [Elao - App] Fix php 8.0+ json extension handling

elao.app/.manala/Dockerfile.tmpl, elao.app/.manala/ansible/inventories/system.yaml.tmpl
Now that apt role respect package installation order (https://github.com/manala/ansible-roles/pull/539), we could install xz-utils using provisionning
=> [Elao - App] Better xz-utils package handling

elao.app/.manala/vagrant/bin/setup.sh.tmpl
Work around an open debian bug where grub panics during an update if the boot disk used during virtual machine image creation is not the same as the disk used during virtual machine running.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982182
=> [Elao - App] Set grub device

elao.app/.manala/docker/make.mk.tmpl
Symptoms:
```Building docker image...
/usr/local/bin/entrypoint.sh: line 26: exec: Use: not found
```
The facts: `docker build --quiet` command is supposed to write image id, and only image id on stdout. On a recent update docker adds some "marketing" stuff on a second line: `Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them`.
Treatment: just keep the first stdout line :)
=> [Elao - App] Fix docker build id

elao.app/.manala/Makefile.tmpl, elao.app/.manala/make/help.mk
Given following project `Makefile` commands:
```
foo:
...
bar.baz:
...
qux.baz:
...
bar.qux:
...
qux.qux:
...
```
This pr tends to enhance commands helps visibility by grouping and ordering messages by "sections". Section names are parsed from messages themselves given the following pattern:
`[Section] - [Message]`
Example:
`## D'assaut - In a bottle`
* Section: "D'assault"
* Message: "In a bottle"
Where our old fashionned and ugly help command used to output this:
```
Usage: make [target]
Help:
help This help
...
Project:
foo:     Foo
bar.baz: Bar - Baz
qux.baz: Qux - Baz
bar.qux: Bar - Qux
qux.qux: Qux - Qux
```
We'll can finally face the challenges of the 21st century:
```
Usage: make [command]
Help:
help This help
...
Commands:
foo: Foo
Bar:
bar.baz: Baz
bar.qux: Qux
Qux:
qux.baz: Baz …
```
=> [Elao - App] Organize make help commands by sections

elao.app/.manala/make/text.mk
Useful in some situations where a make commands NEED some parameters
```
foo:
$(call error_if_not, $(FOO), FOO has not been specified)
echo $(FOO)
```
=> [Elao - App] Make "error_if_not" helper

elao.app/.manala/vagrant/bin/setup.sh.tmpl
Symptom:
```
$ make setup
...
development: [Apt] Update...
development: Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
development: Get:2 http://httpredir.debian.org/debian buster InRelease [122 kB]
development: Get:3 http://httpredir.debian.org/debian buster-updates InRelease [51.9 kB]
development: Reading package lists...
development: E
development: :
development: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
development: E
development: :
development: Repository 'http://httpredir.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
development: E
development: :
development: Repository 'http://httpredir.debian.org/debian …
```
=> [Elao - App] Fix apt update release info change

elao.app/.manala/vagrant/bin/setup.sh.tmpl
"--allow-releaseinfo-change" apt-get option is unavailable on debian stretch
See:
- https://manpages.debian.org/buster/apt/apt-get.8.fr.html
- https://manpages.debian.org/buster/apt/apt-get.8.fr.html
=> [Elao - App] "--allow-releaseinfo-change" apt-get option unavailable on debian stretch

lazy.ansible/.manala/docker-compose.yaml.tmpl, lazy.kubernetes/.manala/docker-compose.yaml.tmpl, lazy.symfony/.manala/docker-compose.yaml.tmpl
Empty env dict produced an invalid docker-compose.yaml file (with a `{}`)
=> [Lazy] Fix env handling

lazy.ansible/.manala/Dockerfile.tmpl, lazy.kubernetes/.manala/Dockerfile.tmpl, lazy.symfony/.manala/Dockerfile.tmpl
Note that `bsdtar` package was a transition package, know available as `libarchive-tools`
=> [Lazy] Update to debian bullseye

elao.app.docker/.manala/Makefile.tmpl
As `github_ssh_key_secret` deliveries key is a must have to let related actions works, we can just rely on its presence to enable makefile triggers or not.
=> [Elao - App - Docker] Github actions triggers

elao.app.docker/.manala.yaml, elao.app.docker/.manala/ansible/inventories/system.yaml.tmpl, elao.app.docker/MIGRATION.2022-02.md, elao.app.docker/README.md
⚠️ ⚠️ ⚠️ 
BC BREAK
⚠️ ⚠️ ⚠️ 
Yarn version 1 (aka. "classic", the only version we support) is in maintenance mode since 2020 (see: https://classic.yarnpkg.com/lang/en/docs/install)
Yarn version 2+ is a p**n in the a*s to install (see: https://yarnpkg.com/getting-started/install)
with this pr, yarn is no more installed by default with nodejs , as an encouragement to STOP using it.
However, one can force its installation if necessary in `.manala.yaml`:
```yaml
system:
...
nodejs:
...
yarn:
version: 1
=> [Elao - App - Docker] Yarn on-demand

elao.app.docker/.manala/docker/make.mk
That was not an easy one, thx @ogizanagi for report.
In a nutshell, by overriding `SSH_AUTH_SOCK` (to handle docker for mac peculiarities, see https://docs.docker.com/desktop/mac/networking/#ssh-agent-forwarding) every single command related to ssh-agent, and runned inside a makefile target had the wrong host `SSH_AUTH_SOCK` value...
This pr respect the same behavior, but in a way that don't globally override `SSH_AUTH_SOCK`. To be more specific, its override it * only * for the docker command itself.
=> [Elao - App - Docker] Fix ssh-agent

elao.app.docker/.manala/github/system/action.yaml
=> [Elao - App - Docker] Optimize github action cache

elao.app.docker/.manala/docker/compose.yaml.tmpl
L'installation des plugins elasticsearch se faisant à l'entrypoint du container, si le plugin est déjà installé, on obtient l'erreur suivante à chaque destroy/setup, car le container est gardé en cache et possède déjà le plugin :
> ERROR: plugin directory [/usr/share/elasticsearch/plugins/analysis-icu] already exists; if you need to update the plugin, uninstall it first using command ‘remove analysis-icu’
empêchant elasticsearch de démarrer.
Corrige en vérifiant la présence du plugin avec `elasticsearch-plugin list` avant l'installation.
=> [Elao - App - Docker] Fix plugin already installed

elao.app.docker/.manala/docker/compose.yaml.tmpl, elao.app.docker/.manala/docker/compose/development.yaml.tmpl, elao.app.docker/.manala/docker/compose/integration.yaml.tmpl, elao.app.docker/.manala/docker/compose/mutagen.yaml.tmpl
As spotted in https://github.com/compose-spec/compose-spec/pull/206/files#diff-5f5b95e68cadf606dc6b4956ca67b87039e3283cb01aa3208fda399abc167906R11 this is no longer necessary with docker compose v2
=> [Elao - App - Docker] Remove docker compose version

elao.app/.manala.yaml, elao.app/.manala/ansible/inventories/system.yaml.tmpl, elao.app/.manala/ansible/system.yaml
The need is to be able to not start the default PhpRedisAdmin container, so we can start another one with custom env to authenticate, in case authentication is set on redis server.
=> [PhpRedisAdmin] Start optionnal

elao.app.docker/.manala/make/help.mk, elao.app/.manala/make/help.mk, lazy.ansible/.manala/make/help.mk, lazy.kubernetes/.manala/make/help.mk, lazy.symfony/.manala/make/help.mk
so targets such as `run-ios-device+release@production` are not ignored
=> [All] Allow + signs in targets appearing in help

elao.app.docker/.manala/ansible/system.yaml
Symptom: you get a 403 from nginx, which is in fact a 404, but nginx don't have the permission to get 404.html file to show you that it's a 404, so you get a 403...
```
⇒  ls -lsa /usr/share/nginx
ls: cannot access '/usr/share/nginx/html': Permission denied
ls: cannot access '/usr/share/nginx/..': Permission denied
ls: cannot access '/usr/share/nginx/.': Permission denied
total 0
? d????????? ? ? ? ?            ? .
? d????????? ? ? ? ?            ? ..
? d????????? ? ? ? ?            ? html
```
In fact, `files` role is played before `nginx` one, so that `/usr/share/nginx` folder does not yet exists. No matter, you will say, `files` role will create it for us
And yes, for sure, it will create it for us, but with the given file permissions, "0644"...
I remember one of my old friends saying …
=> [Elao - App - Docker] Fix nginx 404 file permissions

elao.app.docker/.manala/docker/compose/env.yaml, elao.app.docker/.manala/github/deliveries/README.md.tmpl, elao.app.docker/.manala/github/deliveries/action.yaml.tmpl, elao.app.docker/.manala/github/env/action.yaml, elao.app.docker/.manala/github/system/action.yaml
Alternative to #243 
It has the advantage to make it available using the `./.manala/github/system` action directly and for the whole shell.
Also removes the need for the extra `\` for multiline strings:
```diff
- name: 'Release'
uses: ./.manala/github/deliveries
with:
tier: ${{ github.event.inputs.tier }}
env: |
-            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
+            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
COMPOSER_AUTH=${{ secrets.COMPOSER_AUTH }}
```
Also, as shown below, it allows to expose a new `./.manala/github/system` action to pre-configure secrets for different app / tier / whatever.
```yml
jobs:
release:
steps:
- name: Configure staging secrets
uses: ./.manala/github/env
if: ${{ github.event.inputs.tier == 'staging' }}
with:
env: | …
```
=> [elao.app.docker] Provide a way to forwards secrets as env vars during release/deploy (alternative using .env & env_file)

elao.app.docker/.manala/ansible/roles/release/defaults/main.yml
Fixes #77
On Github CI, `git config --get remote.origin.url` outputs: https://github.com/org/repo [(without the .git)](
https://github.com/actions/checkout/issues/408#issuecomment-1007818466), which cause the regex to fail and the release commit msg to have a double `https://`:
The issue does not happen locally, since it has the `.git` ext, so the `regex_replace` does its job.
Github CI debug with this fix:
=> [Elao - App - Docker] Fixup the release msg commit reference

elao.app.docker/.manala/github/deliveries/README.md.tmpl
https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name
| Après | Avant | Bloopers 😬 |
| - | - | - |
|![SCR-20220927-cq6](https://user-images.githubusercontent.com/2211145/192458185-a66186b4-0a68-4681-97e8-eb2d35d28f4c.png)|![SCR-20220927-cqc](https://user-images.githubusercontent.com/2211145/192458188-1d13d516-97b0-4afe-bd52-1badeb71fa99.png)|![SCR-20220927-cqo](https://user-images.githubusercontent.com/2211145/192458192-fddaaa19-22e9-4345-b857-15c2d60bd817.png)|
=> [Elao - App - Docker] Add workflow run-name for releases to show the target (app+tier)

elao.app.docker/.manala/ansible/roles/release/defaults/main.yml
By using lazy `repository` capturing group:
https://regex101.com/r/gV6FVc/1
=> [Elao - App - Docker] Fix release markup commit URL

elao.app.docker/.manala/ansible/roles/release/tasks/markup.yml
Whenever two jobs are releasing at the same time (ex: api & front apps), one might be behind the other one, and its markup commit would be rejected because the tree is not up-to-date.
Simple solution: let's pull before commit and push.
=> [Elao - App - Docker] Attempt to fix concurrent release markup issues

elao.app.docker/.manala/Jenkinsfile.tmpl, elao.app.docker/.manala/docker/compose.yaml.tmpl, elao.app.docker/.manala/jenkins/Jenkinsfile.tmpl
Use `wait_for_status` param to handle ElasticSearch healthcheck and fix unavailable service bugs at start
=> [Elao - App - Docker] Improve healthchek for Elasticsearch

elao.app.docker/.manala/Makefile.tmpl, elao.app.docker/.manala/github/system/action.yaml
We had an error at starting in a project with ES : container available while the service not yet.
We fix it by removing --detach command in template file for this recipe.
=> [Elao - App - Docker] Edit template to respect healthchecking at containers start

.github/workflows/build_docs.yml, .github/workflows/ci.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> [CI] Fix set-output deprecations

elao.app.docker/.manala.yaml.tmpl, elao.app.docker/README.md
It seems webpack (babel to be precise) put some crap in the `/node_modules/.cache/` directory during asset build process. This cache can be updated at each build/watch with a significant amount of files that could impact mutagen performance.
=> [Elao- App - Docker] Add node_modules cache to suggested mutagen ignore

elao.app.docker/README.md
Mise à jour de la documentation de la recipe `Elao app Docker` - Rubrique `deliveries` : 
- ajout d'un commentaire précisant le rôle de la variable `ref` (le terme `ref` me semblait trop générique et je me demandais pourquoi on ne mettait pas plutôt `branch` qui a l'avantage d'être plus clair)
- dans l'exemple de config d'une delivery, je précise `ref: staging` pour la partie `staging` ... ça me semble une meilleure variable par défaut pour les déploiements en staging que la branche `master` ...
=> [Elao - App - Docker] Update README about delivery ref

elao.app.docker/.manala/docker/make.mk
This one is tricky as hell...
This is a story of enthousiastics developpers who mainly works on MacOS. On MacOS, don't ask me why, the `make` version is stick on stone-age:
```shell
$ make --version
GNU Make 3.81
...
This program built for i386-apple-darwin11.3.0
```
(note the `i386-apple-darwin11.3.0`)
Now, some young hipsters have decided to switch to Linux, especially on ubuntu (22.04) where make version is a bit more decent (4.3)
Nice !
Except for this sneaky bug: https://savannah.gnu.org/bugs/?61309
Long story short, we use shell replacement in makefiles to allow some targets to be played either inside or outside the app container.
Inside the container, we use the builtin shell (`/bin/sh`) and outside the container, we pass the command to docker-compose, to be executed inside the …
=> [Elao - App - Docker] Fix recent make version (4.3+) env parsing with SHELL replacement

elao.app.docker/.manala/github/deliveries/README.md.tmpl
Thanks to https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows 🎉 !
Previously, the sampled release workflow was performing the deploy task, if checked, **in the same workflow**, which is really not awesome, since you don't clearly see it and have to dig **inside the release workflow** run logs.
To circumvent this, I always used a different method to **trigger the deployment workflow from the release workflow**, using the Github API and a Github OAuth app for authentication:
```yaml
- name: 'Get Workflows Knight app token'
id: get_app_token
if: success() && github.event.inputs.deploy == 'true'
uses: machine-learning-apps/actions-app-token@master
with:
APP_PEM: ${{ secrets.WORKFLOWS_KNIGHT_APP_PEM_BASE_64 }}
APP_ID: ${{ secrets.WORKFLOWS_KNIGHT_APP_ID }}
- name: …
```
=> [Elao - App - Docker] Deploy workflow after release separately, using GH CLI

elao.app.docker/.manala/github/reset-stagings/README.md.tmpl
Add a sampled workflow to reset stagings on `master` / `main` branch.
This workflow is useful whenever you want to reset the state of the stagings branches after a release to production, to start over a fresh root.
The workflow allow to:
- Choose which branches to reset (`all`, `staging`, `staging-1`, …) 
| Trigger | All | Single |
| - | - | - |
|![SCR-20221004-o6v](https://user-images.githubusercontent.com/2211145/193860656-a2fd362d-1695-44af-83ba-c9de04d9b3d4.png)|![SCR-20221004-o6d](https://user-images.githubusercontent.com/2211145/193860434-8198c4dd-ddf0-4832-9a1e-de9db2106a36.png) |![SCR-20221004-pgw](https://user-images.githubusercontent.com/2211145/193872555-b9905907-68f9-4cb9-ba5c-91c1c74dab37.png)|
- Choose on which ref it should be reset (default: `master` / `main`)
- Detecting …
=> [Elao - App - Docker] Add a Github Workflow to reset stagings

elao.app.docker/.manala/github/deliveries/README.md.tmpl, elao.app.docker/.manala/github/deliveries/action.yaml.tmpl, elao.app.docker/MIGRATION.2022-11.md
Simplifies the workflow by getting rid of the need for `chrnorm/deployment` actions to create deployment items manually using the Github API.
Instead, rely on the native Github Action environments configuration on the job (`job.<id>.environment`), which automatically creates the deployment item and handle its status according to the workflow execution status.
As a bonus, we have a better notification on Slack, mentioning the app/tier & author:
| Before | After |
| - | - |
|![SCR-20221028-n6w](https://user-images.githubusercontent.com/2211145/198654314-8fcfe067-022f-446f-bf55-feb0d5df77ef.png)|![SCR-20221028-n50](https://user-images.githubusercontent.com/2211145/198654321-41c9cb45-eb08-41ad-bc37-100bd9a4e998.png)|
The workflow also mentions the app URL directly:
| Pending | Done | 
| - | - …
=> [Elao - App - Docker] Use GHA deployment envs

elao.app.docker/.manala/docker/compose/development.yaml.tmpl, elao.app.docker/Makefile.dist
> **Warning**: Tested with most recent versions of Webpack & Encore. Don't assume anything regarding previous versions 😅 
Get rid of HTTPS to HTTP resource loading warnings in dev console by using HTTPS for the dev-server too.
Use more specific allowed hosts, still allowing sub-domains.
=> [Elao - App - Docker] Enhance dev-server target using HTTPS

elao.app.docker/.manala/ansible/roles/release/tasks/main.yml
The warn parameter was remove in ansible 2.14 (disabled & deprecated since ansible 2.11)
See: https://docs.ansible.com/ansible-core/2.13/collections/ansible/builtin/command_module.html#parameter-warn
=> Remove warn option as it's disabled by default

elao.app.docker/.manala/github/deliveries/action.yaml.tmpl
Behavior to test on a real project with latest deploy workflow up-to-date, and without the `deploy_url`
=> [Elao - App - Docker] Optional deploy_url config entry

elao.app.docker/.manala/docker/compose/development.yaml.tmpl
Switch to an alternative docker repository, as there is still no arm support for docker images.
See: https://github.com/mailhog/MailHog/issues/359
Note: entrypoint have been adapted
From `5.1.3` to `5.2.0`
From `1.17.0` to `1.18.0`
From `0.39.0` to `0.44.0`
=> [Elao - App - Docker] Update dev docker images

elao.app.docker/.manala/docker/Dockerfile.tmpl, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.symfony/.manala/docker/Dockerfile.tmpl
- no more too-conscientious `APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE="1"`
- no more too-conscientious `-o=Dpkg::Use-Pty=0`
- `DEBIAN_FRONTEND="noninteractive"` for the masses !
- `--quiet` everywhere
- `--allow-releaseinfo-change` for all updates
- `dist-upgrade` (with `--yes --purge --auto-remove`) after update everywhere
- `--verbose-versions` for all install
=> [All] Harmonize apt-get parameters

lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.ansible/.manala/docker/compose.yaml.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/docker/compose.yaml.tmpl, lazy.symfony/.manala/docker/Dockerfile.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl
Avoid potential issues with incorrect file permissions when using volumes.
=> [Lazy] Handle entrypoint during build

lazy.symfony/.manala/Makefile.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl
```shell
make up WAIT=1
...
make stop
```
This implies:
- having a functionnal healtchek for MariaDB container
- set back the local maildev http port to 1080, so that the internal healthcheck could work
=> [Lazy - Symfony] Introduce up/WAIT and stop make targets

elao.app.docker/.manala/ansible/inventories/system.development.yaml.tmpl, elao.app.docker/.manala/ansible/system.yaml, elao.app.docker/.manala/docker/compose.yaml.tmpl
`/etc/hosts` is read-only in docker containers, but docker (and docker compose) offers a way to add extra hosts via https://docs.docker.com/compose/compose-file/#extra_hosts
=> [Elao - App - Docker] Use native docker network extra hosts

elao.app.docker/.manala/ansible/templates/ssh/development/ssh_config.j2
Mainly
```
HashKnownHosts no
LogLevel ERROR
```
=> [Elao - App - Docker] Better ssh client default config

elao.app.docker/.manala/ansible/ansible.mk
This *SHOULD* solve some of the provision errors due to timeout with ansible galaxy servers
=> [Elao - App - Docker] Increase ansible-galaxy timeout

elao.app.docker/.manala/docker/compose.yaml.tmpl
Elasticsearch 8 comes with security enabled by default, so that https is forced.
To continue to use elasticsearch in development without https, let's force security disablement, even for lower versions.
=> [Elao - App - Docker] Disable elasticsearch security

elao.app.docker/.manala/docker/compose.yaml.tmpl
This is simply not the same as the upper versions :)
=> [Elao - App - Docker] Fix elasticsearch 5 docker command entrypoint

lazy.ansible/.manala.yaml, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.ansible/test/.manala.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.symfony/.manala/docker/Dockerfile.tmpl
- gomplate 3.11.3 -> 3.11.4
- ansible 2.14.2 -> 2.14.3
- ansible-lint 6.12.1 -> 6.14.2
- kubectl 1.26.1 -> 1.26.2
- kubectl 1.25.6 -> 1.25.7
- kubectl 1.24.10 -> 1.24.11
- kubectl 1.23.16-> 1.23.17
- kubectl ~~1.19.16~~
- kubectl ~~1.18.20~~
- helm 3.11.0 -> 3.11.2
- helm ~~3.82~~
- helmfile 0.150.0 -> 0.151.0
- k9s 0.26.7 -> 0.27.3
- stern 1.22.0-> 1.23.0
- popeye 0.10.1 -> 0.11.1
- vault 1.13.0
- vault 1.12.2 -> 1.12.4
- vault 1.11.6 -> 1.11.8
- vault ~~1.10.9~~
- vault ~~1.9.10~~
- openstack 6.0.0 -> 6.2.0
- swift 4.1.0 -> 4.2.0
- swift.keystone 5.0.1 -> 5.1.0
- scw 2.8.0 -> 2.12.0
- aws 2.9.17 -> 2.11.1
=> [Lazy] Update components

lazy.ansible/.manala.yaml, lazy.ansible/.manala.yaml.tmpl, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.ansible/.manala/etc/profile.d/message.sh.tmpl, lazy.ansible/test/.manala.yaml, lazy.ansible/test/goss.yaml
Before:
```yaml
system:
...
molecule:
....
plugins:
version: 23.0.0
docker: true
```
After:
```yaml
system:
...
ansible:
...
dependencies:
- docker==6.0.1
- hvac==1.1.0 
...
molecule:
....
dependencies:
- molecule-plugins==23.0.0
- molecule-plugins[docker]==23.0.0
```
=> [Lazy - Ansible] Pipx and dependencies

lazy.ansible/.manala/gitlab/system.yaml, lazy.kubernetes/.manala/gitlab/system.yaml, lazy.symfony/.manala/gitlab/system.yaml
Not really folichon-folichon, but introduce a way to separate and delegate system setup.
Usage in `.gitlab-ci.yml`:
```yaml
...
include: .manala/gitlab/system.yaml
...
job:
...
before_script:
- !reference [.manala.system.setup, script]
script:
...
```
=> [Lazy] GitLab CI system

elao.app.docker/.manala/docker/compose.yaml.tmpl, lazy.ansible/.manala/docker/compose.yaml.tmpl, lazy.kubernetes/.manala/docker/compose.yaml.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl
Docker compose seems to dislike dots in its name.
`compose.yaml`:
```yaml
name: foo.bar
...
```
> `name Does not match pattern '^[a-z0-9][a-z0-9_-]*$'`
=> [All] No dot in docker compose name

lazy.ansible/.manala/Makefile.tmpl, lazy.kubernetes/.manala/Makefile.tmpl, lazy.symfony/.manala/Makefile.tmpl
Fix xargs interoperability between gnu version (mainly linux) where `-r`  (`--no-run-if-empty`) is mandatory and bsd version (mainly macos) where it's implied.
=> [Lazy] Fix xargs interoperability

elao.app.docker/.manala/github/deliveries/setup/action.yaml.tmpl
Generally speaking, we want : 
- to checkout the `main` / `master` branch for production releases
- to checkout the `staging` branch for staging, staging-1, staging-x releases
- checkout an explicit ref to create a release from when providing a `ref` to the workflow from the UI or command-line / API (`input.ref`)
Hopefully, we already precise the branch to use for the release on each delivery in the `.manala.yaml` config:
```yml
##############
##############
deliveries:
- &delivery_back
app: back
tier: production
ref: main # <- HERE
```
> **Warning**: for repositories with a `master` branch, do precise the `ref: master` entry in the config now rather than leaving empty. 
So we can use this to generate the sub-action to auto-select the proper branch when no `input.ref` is explicitly given. …
=> [Elao - App - Docker] Auto select appropriated ref to checkout for setup & release according to manala.yaml deliveries config

elao.app.docker/Makefile.dist
Just use `make install db` to get back on a project really quick ⚡
=> [Elao - App - Docker] Add convenient db target to reset db + fixtures

lazy.ansible/.manala/etc/profile.d/oh-my-bash.sh.tmpl, lazy.kubernetes/.manala/etc/profile.d/oh-my-bash.sh.tmpl, lazy.symfony/.manala/etc/profile.d/oh-my-bash.sh.tmpl
That was really annoying...
```shell
09:35:55 lazy@foo bar ±| |→ cd baz
/home/foo/bar/baz
09:35:55 lazy@foo baz ±| |→
```
See: https://github.com/ohmybash/oh-my-bash/issues/201
=> [Lazy] Disable full path oh-my-bash print after cd into a directory

lazy.ansible/.manala.yaml, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.ansible/test/.manala.yaml, lazy.ansible/test/goss.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.kubernetes/test/goss.yaml, lazy.symfony/.manala.yaml, lazy.symfony/.manala/docker/Dockerfile.tmpl, lazy.symfony/test/.manala.yaml, lazy.symfony/test/goss.yaml
- gosu 1.16 -> 1.17
- gomplate 3.11.5 -> 3.11.7
- goss 0.4.2 -> 0.4.4
=> [Lazy] Update base components

elao.app.docker/test/goss.yaml
It appears that `ansible` python packages requires `ansible-core` in a semantical version: 
```
'ansible-core ~= 2.15.5',
```
We have to adjust our ansible version test to use regex instead of fixed version.
=> [Elao - App - Docker] Update ansible version test

elao.app.docker/.manala/docker/Dockerfile.tmpl, elao.app.docker/test/Makefile
We are not in a context where final docker images have to be pushed over, and every little byte saved is a victory.
As a consequence, cleaning apt cache after any apt update/install is a nonsense. On the other hand, upgrading apt on the beginning of each layer clearly make sense.
Please, also note that the apt ansible module have issues when updating repositories with an empty `/var/lib/apt/lists` and a fresh modification time. This pr gracefully address this :)
=> [Elao - App - Docker] Optimize docker layers

elao.app.docker/.manala.yaml, elao.app.docker/.manala/ansible/system.yaml, elao.app.docker/.manala/ansible/templates/apt/sources.list.j2, elao.app.docker/.manala/docker/Dockerfile.tmpl, elao.app.docker/README.md, elao.app.docker/test/.manala.yaml, elao.app.docker/test/goss.yaml
=> [Elao - App - Docker] Debian 12

elao.app.docker/.manala/ansible/roles/release/tasks/markup.yml
Same as https://github.com/manala/manala-recipes/pull/432, but for the release markup feature
=> [Elao - App -Docker] Force ansible_facts usage with ansible_date_time

lazy.ansible/.manala.yaml, lazy.ansible/.manala.yaml.tmpl, lazy.ansible/.manala/docker/compose.yaml.tmpl, lazy.ansible/test/.manala.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala.yaml.tmpl, lazy.kubernetes/.manala/docker/compose.yaml.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.symfony/.manala.yaml, lazy.symfony/.manala.yaml.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl, lazy.symfony/test/.manala.yaml
`env_file` could now be set as `required` `true`/`false`
```yaml
...
system:
env_file:
- .env.1
- path: .env.2
required: true
- path: .env.3
required: false
...
```
See: https://docs.docker.com/reference/compose-file/services/#env_file
=> [Lazy] Handle "required" env_file

elao.app.docker/.manala/docker/Dockerfile.tmpl, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.symfony/.manala/docker/Dockerfile.tmpl
Following good practice: https://docs.docker.com/build/building/best-practices/#sort-multi-line-arguments
=> [All] Packages in alphabetical order

lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala.yaml.tmpl, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/.manala/etc/profile.d/message.sh.tmpl, lazy.kubernetes/test/.manala.yaml
The project is abandoned, last version was in 2021 :)
See: https://github.com/c-bata/kube-prompt/releases
=> [Lazy - Kubernetes] Remove kube-prompt

lazy.ansible/.manala/docker/compose/term.yaml, lazy.ansible/.manala/docker/docker.mk, lazy.kubernetes/.manala/docker/compose/term.yaml, lazy.kubernetes/.manala/docker/docker.mk, lazy.symfony/.manala/docker/compose/term.yaml, lazy.symfony/.manala/docker/docker.mk
Pass host TERM environment variable to system container, to benefit - among other things - from more colors in cli when available.
Note that OpenSSH does exactly the same when connecting to an another host.
Note also the default `xterm` TERM we use; docker itself does the same: https://github.com/docker-archive/docker-ce/blob/7772923773ab88e8f7d20528a24f882014e0d8e4/components/engine/container/container.go#L736-L744
=> [Lazy] Use host TERM

lazy.ansible/.manala/docker/compose.yaml.tmpl, lazy.kubernetes/.manala/docker/compose.yaml.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl
Tired of this message during the first build ?
```
! system Warning pull access denied for project, repository does not exist or may require 'docker login': denied: requested access to the resource is denied  
```
Well, docker compose has THE option: https://docs.docker.com/reference/compose-file/services/#pull_policy
"What happen exactly ?" you may ask.
Well, by setting an `image` in the docker compose service with a variable date, we ensure the image will be re-built after each `manala up`. But even if the service has a `build` parameter, docker compose tries to pull the image on the docker registry, leading to the infamous error...
BUT that was BEFORE this marvellous pull request.
=> [Lazy] Stop trying to pull local builded images

elao.app.docker/.manala/ansible/system.yaml
So that phpredisadmin could have access to redis :)
=> [Elao - App - Docker] Disable redis protected mode

.github/workflows/elao.app.docker.yaml, elao.app.docker/.manala/Makefile.tmpl, elao.app.docker/.manala/docker/services/mailpit/compose.yaml.tmpl, elao.app.docker/test/goss.yaml
MailHog is [discontinued](https://github.com/mailhog/MailHog/issues/442#issuecomment-1493415258), replace it by [Mailpit](https://mailpit.axllent.org/)
=> [Elao - App - Docker] Switch to Mailpit

lazy.ansible/.manala/docker/entrypoint.sh, lazy.kubernetes/.manala/docker/entrypoint.sh, lazy.symfony/.manala/docker/entrypoint.sh
Encapsulate variables with double quotes to prevent evaluation issues
=> [Lazy] Cleanup entrypoints

lazy.ansible/.manala/etc/zsh/.zshrc.tmpl, lazy.kubernetes/.manala/etc/zsh/.zshrc.tmpl, lazy.symfony/.manala/etc/zsh/.zshrc.tmpl
See: https://seankhliao.com/blog/12021-07-29-makefile-notes/#-zsh--completion
> zsh has built in support for extracting targets from Makefiles for autocompletion. Unfortunately, it can more or less only extract the statically defined targets. If you use patterns, wildcards, etc., you'll have to actually execute make to generate targets. Also, you'll likely want to skip the builtin make variables as autocomplete targets.
=> [Lazy] Enhanced zsh make completion

elao.app.docker/.manala/github/system/setup/action.yaml, lazy.ansible/.manala/github/system/setup/action.yaml, lazy.kubernetes/.manala/github/system/setup/action.yaml, lazy.symfony/.manala/github/system/setup/action.yaml
As long as the docker compose version available on github action runners is not >=  2.33.1, github action cache version could not be detected with the help of `ACTIONS_CACHE_SERVICE_V2` environment variable.
So we trick it by forcing the usage of `url_v2` parameter.
See: https://github.com/moby/buildkit/issues/5896
=> [All] Use github action cache v2

elao.app.docker/.manala/docker/Dockerfile.tmpl
Fix
```
[DEPRECATION WARNING]: community.general.yaml has been deprecated. The plugin 
has been superseded by the the option `result_format=yaml` in callback plugin 
ansible.builtin.default from ansible-core 2.13 onwards. This feature will be 
removed from community.general in version 13.0.0. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```
=> [Elao - App - Docker] Fix ansible yaml result deprecation

lazy.ansible/.manala.yaml, lazy.ansible/.manala/docker/Dockerfile.tmpl, lazy.ansible/test/.manala.yaml, lazy.ansible/test/goss.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala/docker/Dockerfile.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.kubernetes/test/goss.yaml, lazy.symfony/.manala.yaml, lazy.symfony/.manala/docker/Dockerfile.tmpl, lazy.symfony/test/.manala.yaml, lazy.symfony/test/goss.yaml
Notes:
- Switch to `gosu` debian package, now available in a decent version in debian repository
- Update `lazy.symfony` `nginx` component to version `1.28`, the minimum version available in nginx trixie packages repository
- Remove `goss` as component, must now be installed as an apt package
```yaml
system:
goss:
version: 0.4.9
apt:
packages:
- goss
```
=> [Lazy] Update to Debian Trixie

lazy.ansible/.manala.yaml, lazy.ansible/.manala.yaml.tmpl, lazy.ansible/.manala/docker/compose.yaml.tmpl, lazy.ansible/test/.manala.yaml, lazy.ansible/test/goss.yaml, lazy.kubernetes/.manala.yaml, lazy.kubernetes/.manala.yaml.tmpl, lazy.kubernetes/.manala/docker/compose.yaml.tmpl, lazy.kubernetes/test/.manala.yaml, lazy.kubernetes/test/goss.yaml, lazy.symfony/.manala.yaml, lazy.symfony/.manala.yaml.tmpl, lazy.symfony/.manala/docker/compose.yaml.tmpl, lazy.symfony/test/.manala.yaml, lazy.symfony/test/goss.yaml
Rollback on https://github.com/manala/manala-recipes/pull/508, and more !
Having a static `/tmp` as a tmpfs, is not flexible enough :( What about having others ? What about options such as `exec`/`noexec` ?
This PR removes the  static `/tmp`tmpfs  and introduces a new `tmpfs` option, directly mapped on docker compose on (see: https://docs.docker.com/reference/compose-file/services/#tmpfs)
```
system:
tmpfs:
- /tmp
- /foo/bar:exec
```
=> [Lazy] Tmpfs

lazy.ansible/.manala/docker/Dockerfile.tmpl
According to the documentation:
> If you want to install the exact versions of all dependencies that were used to test a specific version of ansible-lint, you can add lock extra. This will only work with Python 3.10 or newer. Do this only inside a virtual environment.
This should keep us away from some dependencies nightmares :)
=> [Lazy - Ansible] Use ansible-lint lock extra
